package myPackage8;


import java.util.*;
public class Source{
	
	static int n;
    public static int getN() {
		return n;
	}
	public static void setN(int n) {
		Source.n = n;
	}
	
	static Object lock = new Object();

    
    public static void main(String[] args) {
    	
    	
        Thread t1 = new Thread(new Runnable(){
        	public void run()
        	{
        		synchronized (lock) {
        			Scanner sc=new Scanner(System.in);
            		System.out.println("Enter number");
            		int n=sc.nextInt();
            		setN(n);
            		sc.close();
				}
        		
        	}
        });

        Thread t2 = new Thread(new Runnable(){ 
        	public void run()
    		{
        		synchronized (lock)
        		{
        			// complete this function!
        			int n=getN();
        			 if (n==0)
        			 {
        				 System.out.println(1);
        			 }
        			 else
        			 {
        				   int fact=1,i;
                    	   for(i=1;i<=n;i++)
                    	   {
                    		   fact=fact*i;
                    	   }
        				 System.out.println("Factorial is "+fact);
        			 }
        			 
        		}
    		}
        	});

        try {
            t1.start();
            t2.start();
            t1.join();
            t2.join();
        } catch (Exception e) {
            System.out.println("An exception has occured!");
        }
    }
}